= LITERATURE REVIEW
== Historical Evolution 
Traditional parking systems before the early 2000s relied on manual ticketing and human-based billing, often leading to errors, congestion, and poor record keeping. In the early 2000s, semi-automated systems using barcode or RFID tickets improved accuracy but remained costly and hardware-dependent. During the 2010s, camera-based ANPR using basic image processing and OCR enabled contactless vehicle identification, though performance was sensitive to lighting and camera angles. With the rapid advancement of deep learning, modern approaches using CNN-based object detection models @CNN such as YOLO combined with OCR significantly enhanced detection accuracy and real-time processing, forming the foundation of Real-Time Smart Parking Billing System Using YOLO and OCR.

== Algorithms and Model
The proposed system employs a deep learning based ANPR pipeline that integrates object detection, character recognition, and automated billing. For license plate detection, the system uses the YOLO  algorithm, a single-stage CNN-based object detection model that divides an image into grids and predicts bounding boxes and class probabilities in one pass, enabling fast and accurate real-time detection of number plates. Once the plate is detected, it is cropped and preprocessed using OpenCV techniques such as grayscale conversion, resizing, noise reduction, and thresholding to enhance character visibility. For character recognition, the system applies OCR, supported by CNN-based models, to extract alphanumeric characters from the processed plate image. The recognized license number is then stored in a database along with entry and exit timestamps, and a billing algorithm computes parking charges based on the duration of stay. This integrated model ensures efficient, accurate, and automated parking billing with minimal human intervention.

== Data Pre-Processing and Feature Engineering
In the proposed system, data pre-processing is essential for improving the accuracy of license plate detection and character recognition. After image acquisition, vehicle images are enhanced using OpenCV techniques, including resizing to a fixed resolution, grayscale conversion to reduce computational load, and noise reduction to minimize distortions caused by lighting variations or motion blur. Thresholding and contrast enhancement are applied to clearly separate license plate characters from the background, improving recognition reliability.

Feature engineering is handled automatically using CNNs rather than manual feature design. In the YOLO-based detection stage, the model learns spatial features such as edges, contours, and plate-like patterns to accurately localize license plates. During the OCR stage, CNN models extract character-level features, including stroke and shape patterns, enabling accurate recognition across different fonts, plate styles, and lighting conditions. The processed data is then forwarded to the recognition and billing modules, ensuring consistent and reliable system performance.

== Gap and Challenges 
Despite advances in ANPR-based parking systems, several gaps remain. In many developing regions, traditional and semi-automated parking methods are still common, resulting in inefficiencies, billing errors, and limited transparency. Even existing camera-based ANPR systems often struggle under real-world conditions such as poor lighting, motion blur, angled or damaged plates, and inconsistent number plate formats—challenges that are particularly relevant in the Nepali context. OCR models may also face difficulties in character segmentation and distinguishing similar-looking alphanumeric characters, reducing recognition accuracy. Additionally, high hardware costs, scalability issues, and data privacy concerns restrict large-scale deployment. These limitations highlight the need for a robust, low-cost, deep learning–based solution capable of operating reliably in uncontrolled environments with minimal human intervention.